### ISSUE TITLE
JuliaRL_A2C_CartPole experiment hook TotalRewardPerEpisode not work

### ISSUE THREAD

**Issue by zzh237** [JuliaReinforcementLearning/ReinforcementLearningZoo.jl#168]
This is my script for running:

id = "JuliaRL_A2C_CartPole"
e = Experiment(id)
agent = e.policy 
env = e.env 
stop_condition = e.stop_condition
hook = TotalRewardPerEpisode()
run(agent, env, stop_condition, hook)
rewards = hook.rewards

and it gives me error as:

LoadError: MethodError: no method matching +(::Float64, ::Vector{Float32})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array

And I found that the error is from line 139 in hook.jl:

function (hook::TotalRewardPerEpisode)(::PostActStage, agent, env)
    hook.reward += reward(env)
end

the reward(env) returns a vector: 
Float32[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

I didn't change any code, and I just use the newest package by add ReinforcementLearning#master

**Comment by albheim** [comment]
The TotalRewardPerEpisode assumes a scalar reward from the reward(env) call, see

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/c14ec876311408096a677f1b998e307cafff4dc4/src/core/hooks.jl#L124

Just running `run(e)` after defining the experiment works and will collect the reward for each environment, but since this is running multiple environments, see

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/rl_envs/JuliaRL_A2C_CartPole.jl

we instead use a TotalBatchRewardPerEpisode that takes an array of rewards from each environment, see

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/c14ec876311408096a677f1b998e307cafff4dc4/src/core/hooks.jl#L152

so that is why it did not work.

**Comment by albheim** [comment]
This works for me
```julia
id = "JuliaRL_A2C_CartPole"
e = Experiment(id)
agent = e.policy
env = e.env
stop_condition = e.stop_condition
hook = TotalBatchRewardPerEpisode(length(e.env)) # Keep track of reward for each env
run(agent, env, stop_condition, hook)
rewards = hook.rewards
```
